using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NetCore.Microservices.Services.ShoppingCartApi.Migrations
{
    /// <inheritdoc />
    public partial class UpdateAutoGeneratedId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "Id",
                table: "CartHeader",
                newName: "CartHeaderId");

            migrationBuilder.RenameColumn(
                name: "Id",
                table: "CartDetails",
                newName: "CartDetailsId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "CartHeaderId",
                table: "CartHeader",
                newName: "Id");

            migrationBuilder.RenameColumn(
                name: "CartDetailsId",
                table: "CartDetails",
                newName: "Id");
        }
    }
}
