using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NetCore.Microservices.Services.CouponApi.Migrations
{
    /// <inheritdoc />
    public partial class AutoGeneratedCouponId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
